[profile.default]
src = "src"
out = "out"
libs = ["lib"]
show_progress = true

# include remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/",
    "@chimera/=lib/chimera/src/",
]

[fuzz]
runs = 500
max_test_rejects = 999999999

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
